=begin
#DQT API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v2

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

require 'date'
require 'time'

module OpenapiClient
  class ClassDivision
    FIRST_CLASS_HONOURS = "FirstClassHonours".freeze
    UPPER_SECOND_CLASS_HONOURS = "UpperSecondClassHonours".freeze
    LOWER_SECOND_CLASS_HONOURS = "LowerSecondClassHonours".freeze
    UNDIVIDED_SECOND_CLASS_HONOURS = "UndividedSecondClassHonours".freeze
    THIRD_CLASS_HONOURS = "ThirdClassHonours".freeze
    FOURTH_CLASS_HONOURS = "FourthClassHonours".freeze
    UNCLASSIFIED_HONOURS = "UnclassifiedHonours".freeze
    AEGROTAT = "Aegrotat".freeze
    PASS_FOLLOWING_AN_HONOURS_COURSE = "PassFollowingAnHonoursCourse".freeze
    ORDINARY = "Ordinary".freeze
    GENERAL_DEGREE = "GeneralDegree".freeze
    DISTINCTION = "Distinction".freeze
    MERIT = "Merit".freeze
    PASS = "Pass".freeze
    NOTAPPLICABLE = "Notapplicable".freeze
    NOT_KNOWN = "NotKnown".freeze
    HIGHER_DEGREE = "HigherDegree".freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = ClassDivision.constants.select { |c| ClassDivision::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #ClassDivision" if constantValues.empty?
      value
    end
  end
end
