=begin
#DQT API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v2

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

require 'date'
require 'time'

module OpenapiClient
  class GetOrCreateTrnRequestInitialTeacherTraining
    attr_accessor :provider_ukprn

    attr_accessor :programme_start_date

    attr_accessor :programme_end_date

    attr_accessor :programme_type

    attr_accessor :subject1

    attr_accessor :subject2

    attr_accessor :age_range_from

    attr_accessor :age_range_to

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'provider_ukprn' => :'providerUkprn',
        :'programme_start_date' => :'programmeStartDate',
        :'programme_end_date' => :'programmeEndDate',
        :'programme_type' => :'programmeType',
        :'subject1' => :'subject1',
        :'subject2' => :'subject2',
        :'age_range_from' => :'ageRangeFrom',
        :'age_range_to' => :'ageRangeTo'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'provider_ukprn' => :'String',
        :'programme_start_date' => :'Date',
        :'programme_end_date' => :'Date',
        :'programme_type' => :'IttProgrammeType',
        :'subject1' => :'String',
        :'subject2' => :'String',
        :'age_range_from' => :'Integer',
        :'age_range_to' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'subject1',
        :'subject2',
        :'age_range_from',
        :'age_range_to'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpenapiClient::GetOrCreateTrnRequestInitialTeacherTraining` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpenapiClient::GetOrCreateTrnRequestInitialTeacherTraining`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'provider_ukprn')
        self.provider_ukprn = attributes[:'provider_ukprn']
      end

      if attributes.key?(:'programme_start_date')
        self.programme_start_date = attributes[:'programme_start_date']
      end

      if attributes.key?(:'programme_end_date')
        self.programme_end_date = attributes[:'programme_end_date']
      end

      if attributes.key?(:'programme_type')
        self.programme_type = attributes[:'programme_type']
      end

      if attributes.key?(:'subject1')
        self.subject1 = attributes[:'subject1']
      end

      if attributes.key?(:'subject2')
        self.subject2 = attributes[:'subject2']
      end

      if attributes.key?(:'age_range_from')
        self.age_range_from = attributes[:'age_range_from']
      end

      if attributes.key?(:'age_range_to')
        self.age_range_to = attributes[:'age_range_to']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @provider_ukprn.nil?
        invalid_properties.push('invalid value for "provider_ukprn", provider_ukprn cannot be nil.')
      end

      if @programme_start_date.nil?
        invalid_properties.push('invalid value for "programme_start_date", programme_start_date cannot be nil.')
      end

      if @programme_end_date.nil?
        invalid_properties.push('invalid value for "programme_end_date", programme_end_date cannot be nil.')
      end

      if @programme_type.nil?
        invalid_properties.push('invalid value for "programme_type", programme_type cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @provider_ukprn.nil?
      return false if @programme_start_date.nil?
      return false if @programme_end_date.nil?
      return false if @programme_type.nil?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          provider_ukprn == o.provider_ukprn &&
          programme_start_date == o.programme_start_date &&
          programme_end_date == o.programme_end_date &&
          programme_type == o.programme_type &&
          subject1 == o.subject1 &&
          subject2 == o.subject2 &&
          age_range_from == o.age_range_from &&
          age_range_to == o.age_range_to
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [provider_ukprn, programme_start_date, programme_end_date, programme_type, subject1, subject2, age_range_from, age_range_to].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = OpenapiClient.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
