=begin
#DQT API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v2

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::IttOutcomeApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'IttOutcomeApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::IttOutcomeApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of IttOutcomeApi' do
    it 'should create an instance of IttOutcomeApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::IttOutcomeApi)
    end
  end

  # unit tests for v2_teachers_trn_itt_outcome_put
  # Sets ITT outcome for a teacher
  # @param trn The TRN of the teacher to set ITT outcome for.
  # @param [Hash] opts the optional parameters
  # @option opts [SetIttOutcomeRequest] :set_itt_outcome_request 
  # @return [SetIttOutcomeResponse]
  describe 'v2_teachers_trn_itt_outcome_put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
