=begin
#DQT API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v2

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::TeachersApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'TeachersApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::TeachersApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TeachersApi' do
    it 'should create an instance of TeachersApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::TeachersApi)
    end
  end

  # unit tests for v2_teachers_find_get
  # Returns teachers matching the specified criteria
  # @param [Hash] opts the optional parameters
  # @option opts [String] :email_address Email Address
  # @option opts [String] :first_name First name of person
  # @option opts [String] :middle_name Middle name of person
  # @option opts [String] :last_name Last name of person
  # @option opts [String] :previous_first_name Previous first name of person
  # @option opts [String] :previous_last_name Previous last name of person
  # @option opts [Date] :date_of_birth Date of birth of person
  # @option opts [String] :national_insurance_number National insurance number of person
  # @option opts [String] :itt_provider_name Name of teacher training provider
  # @option opts [String] :itt_provider_ukprn UKPRN of teacher training provider
  # @return [FindTeachersResponse]
  describe 'v2_teachers_find_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
