=begin
#DQT API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v2

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::TrnRequestsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'TrnRequestsApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::TrnRequestsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TrnRequestsApi' do
    it 'should create an instance of TrnRequestsApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::TrnRequestsApi)
    end
  end

  # unit tests for v2_trn_requests_request_id_get
  # Retrieves a TRN request
  # @param request_id The unique ID the TRN request was created with.
  # @param [Hash] opts the optional parameters
  # @return [TrnRequestInfo]
  describe 'v2_trn_requests_request_id_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v2_trn_requests_request_id_put
  # Creates a request for a TRN
  # @param request_id A unique ID that represents this request. If a request has already been created with this ID then that existing record&#39;s result is returned.
  # @param [Hash] opts the optional parameters
  # @option opts [GetOrCreateTrnRequest] :get_or_create_trn_request 
  # @return [TrnRequestInfo]
  describe 'v2_trn_requests_request_id_put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
