=begin
#DQT API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v2

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::UnlockTeacherApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'UnlockTeacherApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::UnlockTeacherApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of UnlockTeacherApi' do
    it 'should create an instance of UnlockTeacherApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::UnlockTeacherApi)
    end
  end

  # unit tests for v2_unlock_teacher_teacher_id_put
  # Unlocks the teacher record allowing the teacher to sign in to the portals
  # @param teacher_id The ID of the teacher record to unlock
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'v2_unlock_teacher_teacher_id_put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
