=begin
#DQT API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v2

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::GetIttProvidersResponse
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::GetIttProvidersResponse do
  let(:instance) { OpenapiClient::GetIttProvidersResponse.new }

  describe 'test an instance of GetIttProvidersResponse' do
    it 'should create an instance of GetIttProvidersResponse' do
      expect(instance).to be_instance_of(OpenapiClient::GetIttProvidersResponse)
    end
  end
  describe 'test attribute "itt_providers"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
