=begin
#DQT API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v2

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::IttProgrammeType
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::IttProgrammeType do
  let(:instance) { OpenapiClient::IttProgrammeType.new }

  describe 'test an instance of IttProgrammeType' do
    it 'should create an instance of IttProgrammeType' do
      expect(instance).to be_instance_of(OpenapiClient::IttProgrammeType)
    end
  end
end
