=begin
#DQT API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v2

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::SetIttOutcomeResponse
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::SetIttOutcomeResponse do
  let(:instance) { OpenapiClient::SetIttOutcomeResponse.new }

  describe 'test an instance of SetIttOutcomeResponse' do
    it 'should create an instance of SetIttOutcomeResponse' do
      expect(instance).to be_instance_of(OpenapiClient::SetIttOutcomeResponse)
    end
  end
  describe 'test attribute "trn"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "qts_date"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
