=begin
#DQT API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v2

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

# Common files
require 'openapi_client/api_client'
require 'openapi_client/api_error'
require 'openapi_client/version'
require 'openapi_client/configuration'

# Models
require 'openapi_client/models/class_division'
require 'openapi_client/models/find_teacher_result'
require 'openapi_client/models/find_teachers_response'
require 'openapi_client/models/gender'
require 'openapi_client/models/get_itt_providers_response'
require 'openapi_client/models/get_or_create_trn_request'
require 'openapi_client/models/get_or_create_trn_request_address'
require 'openapi_client/models/get_or_create_trn_request_initial_teacher_training'
require 'openapi_client/models/get_or_create_trn_request_qualification'
require 'openapi_client/models/itt_outcome'
require 'openapi_client/models/itt_programme_type'
require 'openapi_client/models/itt_provider_info'
require 'openapi_client/models/problem_details'
require 'openapi_client/models/set_itt_outcome_request'
require 'openapi_client/models/set_itt_outcome_response'
require 'openapi_client/models/trn_request_info'
require 'openapi_client/models/trn_request_status'

# APIs
require 'openapi_client/api/itt_outcome_api'
require 'openapi_client/api/itt_providers_api'
require 'openapi_client/api/teachers_api'
require 'openapi_client/api/trn_requests_api'
require 'openapi_client/api/unlock_teacher_api'

module OpenapiClient
  class << self
    # Customize default settings for the SDK using block.
    #   OpenapiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
